 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: pasifik                                                     
     # Surfaces =   5
     # Strips   =  82
     # Vortices = 752

  Sref = 0.83750       Cref = 0.34220       Bref =  2.5000    
  Xref = 0.12500       Yref =  0.0000       Zref =-0.30000E-02

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -0.40044     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.01485     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =   0.02242
  CZtot =  -0.49621     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.49630
  CDtot =   0.01138
  CDvis =   0.00000     CDind = 0.0113838
  CLff  =   0.49622     CDff  = 0.0114261    | Trefftz
  CYff  =  -0.00000         e =    0.9192    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.119921    CLb =   0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.131047
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.031584
 y  mom.  Cm |    Cma =  -1.304133    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.045272

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   9.566026    CLr =   0.000000
 y  force CY |    CYp =   0.079825    CYq =   0.000000    CYr =   0.093940
 x' mom.  Cl'|    Clp =  -0.481888    Clq =   0.000000    Clr =   0.132501
 y  mom.  Cm |    Cmp =   0.000000    Cmq = -16.797850    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.037314    Cnq =  -0.000000    Cnr =  -0.037488

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.009011   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000390   CYd02 =  -0.000000   CYd03 =  -0.001533
 x' mom.  Cl'|   Cld01 =  -0.006739   Cld02 =  -0.000000   Cld03 =  -0.000137
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.029536   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =   0.000203   Cnd02 =  -0.000000   Cnd03 =   0.000564
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000059 CDffd03 =  -0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.028535    ed03 =   0.000000



 Neutral point  Xnp =   0.212164

 Clb Cnr / Clr Cnb  =   0.197384    (  > 1 if spirally stable )
