 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: pasifik                                                     
     # Surfaces =   5
     # Strips   =  82
     # Vortices = 752

  Sref = 0.83750       Cref = 0.34220       Bref =  2.5000    
  Xref = 0.12500       Yref =  0.0000       Zref =-0.30000E-02

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.01421     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =  -0.13357
  CZtot =  -0.57701     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.57701
  CDtot =   0.01421
  CDvis =   0.00000     CDind = 0.0142056
  CLff  =   0.57701     CDff  = 0.0142492    | Trefftz
  CYff  =  -0.00000         e =    0.9966    | Plane  

   aileron         =   0.00000
   elevator        =   5.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.112079    CLb =   0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.130491
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.036319
 y  mom.  Cm |    Cma =  -1.319981    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.045196

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   9.402126    CLr =   0.000000
 y  force CY |    CYp =   0.090181    CYq =   0.000000    CYr =   0.093064
 x' mom.  Cl'|    Clp =  -0.481163    Clq =  -0.000000    Clr =   0.143316
 y  mom.  Cm |    Cmp =   0.000000    Cmq = -16.370434    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.042281    Cnq =  -0.000000    Cnr =  -0.037826

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.009012   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000380   CYd02 =  -0.000000   CYd03 =  -0.001524
 x' mom.  Cl'|   Cld01 =  -0.006730   Cld02 =  -0.000000   Cld03 =  -0.000136
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.029405   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =   0.000189   Cnd02 =   0.000000   Cnd03 =   0.000561
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000432 CDffd03 =   0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.000805    ed03 =  -0.000000



 Neutral point  Xnp =   0.213359

 Clb Cnr / Clr Cnb  =   0.212091    (  > 1 if spirally stable )
