 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: gokce                                                       
     # Surfaces =   5
     # Strips   =  82
     # Vortices = 752

  Sref = 0.63950       Cref = 0.34570       Bref =  1.8800    
  Xref = 0.80700E-01   Yref =  0.0000       Zref = -0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   2.32186     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.00696     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =  -0.00000     Cmtot =  -0.00844
  CZtot =  -0.43487     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   0.43480
  CDtot =   0.01066
  CDvis =   0.00000     CDind = 0.0106617
  CLff  =   0.43523     CDff  = 0.0114980    | Trefftz
  CYff  =  -0.00000         e =    0.9488    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.391947    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.199703
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.033426
 y  mom.  Cm |    Cma =  -0.658503    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.101882

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   7.705514    CLr =  -0.000000
 y  force CY |    CYp =   0.156452    CYq =   0.000000    CYr =   0.202149
 x' mom.  Cl'|    Clp =  -0.417107    Clq =   0.000000    Clr =   0.107153
 y  mom.  Cm |    Cmp =   0.000000    Cmq =  -9.617536    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.063133    Cnq =  -0.000000    Cnr =  -0.107912

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.007330   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000505   CYd02 =   0.000000   CYd03 =  -0.002251
 x' mom.  Cl'|   Cld01 =  -0.004683   Cld02 =  -0.000000   Cld03 =  -0.000078
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.020990   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000129   Cnd02 =  -0.000000   Cnd03 =   0.001180
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =  -0.000078 CDffd03 =  -0.000000
 span eff.   |    ed01 =  -0.000000    ed02 =   0.038455    ed03 =   0.000000



 Neutral point  Xnp =   0.132532

 Clb Cnr / Clr Cnb  =   0.330409    (  > 1 if spirally stable )
