 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: gokce                                                       
     # Surfaces =   5
     # Strips   =  82
     # Vortices = 752

  Sref = 0.63950       Cref = 0.34570       Bref =  1.8800    
  Xref = 0.80700E-01   Yref =  0.0000       Zref = -0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00500     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =  -0.08685
  CZtot =  -0.29290     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   0.29290
  CDtot =   0.00500
  CDvis =   0.00000     CDind = 0.0049967
  CLff  =   0.29290     CDff  = 0.0046553    | Trefftz
  CYff  =  -0.00000         e =    1.0614    | Plane  

   aileron         =   0.00000
   elevator        =   5.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.420376    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.201884
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.020986
 y  mom.  Cm |    Cma =  -0.659187    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.101442

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   7.719425    CLr =  -0.000000
 y  force CY |    CYp =   0.119629    CYq =   0.000000    CYr =   0.210006
 x' mom.  Cl'|    Clp =  -0.418587    Clq =   0.000000    Clr =   0.073821
 y  mom.  Cm |    Cmp =   0.000000    Cmq =  -9.625438    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.051447    Cnq =  -0.000000    Cnr =  -0.107872

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.007349   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000559   CYd02 =   0.000000   CYd03 =  -0.002284
 x' mom.  Cl'|   Cld01 =  -0.004707   Cld02 =  -0.000000   Cld03 =  -0.000083
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.021025   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000096   Cnd02 =  -0.000000   Cnd03 =   0.001197
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000114 CDffd03 =  -0.000000
 span eff.   |    ed01 =  -0.000000    ed02 =   0.027373    ed03 =   0.000000



 Neutral point  Xnp =   0.132252

 Clb Cnr / Clr Cnb  =   0.302298    (  > 1 if spirally stable )
